import { Stack, StackProps } from 'aws-cdk-lib';
import type { Construct } from 'constructs';
// import { StringParameter } from 'aws-cdk-lib/aws-ssm';
// import { NagSuppressions } from 'cdk-nag';

import { DataAsset } from "./dataAsset.construct.js";
import { dfEventBusName, OrganizationUnitPath } from '@df/cdk-common';

export type DataAssetStackProperties = StackProps & {
    moduleName:string;
    orgPath: OrganizationUnitPath;
    hubAccountId: string;
};


export class DataAssetStack extends Stack {
    constructor(scope: Construct, id: string, props: DataAssetStackProperties) {
        super(scope, id, props);

        new DataAsset(this, 'DataAsset', {
            moduleName: props.moduleName,
            eventBusName: dfEventBusName,
            orgPath: props.orgPath,
            hubAccountId: props.hubAccountId
        });

    //     NagSuppressions.addResourceSuppressionsByPath(this,'/DataAssetStack/LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole/DefaultPolicy/Resource',
    //     [
    //         {
    //             id: 'AwsSolutions-IAM4',
    //             appliesTo: ['Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
    //             reason: 'This policy is the one generated by CDK.'

    //         }, 
    //         {
    //             id: 'AwsSolutions-IAM5',
    //             appliesTo: ['Resource::*'
    //             ],
    //             reason: 'The resource condition in the IAM policy is generated by CDK, this only applies to xray:PutTelemetryRecords and xray:PutTraceSegments actions.'

    //         }
    //     ],
    //     true);

    //     NagSuppressions.addResourceSuppressionsByPath(this,'/DataAssetStack/LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole/Resource',
    //     [
    //         {
    //             id: 'AwsSolutions-IAM4',
    //             appliesTo: ['Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
    //             reason: 'This policy is the one generated by CDK.'

    //         }
    //     ],
    //     true);
    
    }
}
