import { Stack, StackProps } from 'aws-cdk-lib';
import { NagSuppressions } from 'cdk-nag';
import type { Construct } from 'constructs';
import { CognitoIdpCreator } from './cognitoIdpCreator.construct.js';




export type CognitoCustomStackProperties = StackProps & {
	environment: string;
	samlMetaDataUrl?: string;
	ssoRegion: string;
	userPoolIdParameter: string;
};


export class CognitoCustomStack extends Stack {
	constructor(scope: Construct, id: string, props: CognitoCustomStackProperties) {
		super(scope, id, props);

		// validation
		if (props.environment === undefined) {
			throw new Error('environment is required');
		}
	
		if (props.samlMetaDataUrl){
			// SAML metadata available deploy federated cognito

			new CognitoIdpCreator(this,'CognitoIdpCreator',{
				environment: props.environment,
				userPoolIdParameter: props.userPoolIdParameter,
				samlMetaDataUrl: props.samlMetaDataUrl
			});


		}
		

		NagSuppressions.addResourceSuppressionsByPath(this, [
				'/CognitoCustomStack/CognitoIdpCreator/CognitoIdpCreatorLambda/ServiceRole/DefaultPolicy/Resource'
			],
			[
				{
					id: 'AwsSolutions-IAM4',
					appliesTo: ['Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
					reason: 'This policy attached to the role is generated by CDK.'

				},
				{
					id: 'AwsSolutions-IAM5',
					appliesTo: ['Resource::arn:aws:ssm:<AWS::Region>:<AWS::AccountId>:*'],
					reason: 'This resource condition allows access to ssm parameters related to the project.'

				},
				{
					id: 'AwsSolutions-IAM5',
					appliesTo: ['Resource::*'],
					reason: 'This resource condition in the IAM policy is generated by CDK, this only applies to logs:DeleteRetentionPolicy and logs:PutRetentionPolicy actions.'

				}],
			true);

			NagSuppressions.addResourceSuppressionsByPath(this, [
				'/CognitoCustomStack/LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole/Resource',
			],
			[
				{
					id: 'AwsSolutions-IAM4',
					appliesTo: ['Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
					reason: 'This policy attached to the role is generated by CDK.'

				}],
			true);

			NagSuppressions.addResourceSuppressionsByPath(this, [
				'/CognitoCustomStack/LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole/DefaultPolicy/Resource'
			],
			[
				{
					id: 'AwsSolutions-IAM5',
					appliesTo: ['Resource::*'],
					reason: 'This resource condition in the IAM policy is generated by CDK, this only applies to logs:DeleteRetentionPolicy and logs:PutRetentionPolicy actions.'

				}],
			true);
	}
}
